In [156]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n
import math

In [120]:
d = pd.read_csv('hiring.csv')

In [121]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [122]:
d['experience'] = d['experience'].fillna('zero')

In [123]:
d.experience = d.experience.apply(w2n.word_to_num)

In [125]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [132]:
d.rename(columns={'test_score(out of 10)':'test_score', 'interview_score(out of 10)':'interview_score', 'salary($)':'salary'}, inplace = True)

In [135]:
d

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [163]:
d['test_score'].median()

8.0

In [145]:
d['test_score'] = d['test_score'].fillna('8.0')

In [146]:
d

experience test_score  interview_score  salary
0           0        8.0                9   50000
1           0        8.0                6   45000
2           5        6.0                7   60000
3           2       10.0               10   65000
4           7        9.0                6   70000
5           3        7.0               10   62000
6          10        8.0                7   72000
7          11        7.0                8   80000

In [150]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score','interview_score']], d.salary)

LinearRegression()

In [151]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [152]:
reg.intercept_

17737.26346433771

In [153]:
reg.predict([['2','9','6']])

/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([53205.96797671])

In [155]:
reg.predict([['12','10','10']])

/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([92002.18340611])